/**
 * Cross-engine parity: replay the golden fixtures generated by the Go test
 * suite (crdt/testdata/text_golden.json) and assert identical visible
 * state. If this fails after a Go-side change, regenerate the fixtures by
 * running the Go tests (`go test ./crdt/ -run TestText_GoldenFixtures`).
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import type { HLC, TextOperation, TextDeltaSegment } from "../types.js";
import { newTextState, applyTextOp, textValue, textDelta } from "../text.js";

interface GoldenRec {
  node_id: string;
  hlc: HLC;
  op: TextOperation;
}

interface GoldenCase {
  name: string;
  records: GoldenRec[];
  expected_value: string;
  expected_delta: TextDeltaSegment[] | null;
}

const fixturePath = join(
  dirname(fileURLToPath(import.meta.url)),
  "../../../crdt/testdata/text_golden.json"
);

const cases: GoldenCase[] = JSON.parse(readFileSync(fixturePath, "utf8"));

describe("Go/TS text golden parity", () => {
  it("has fixtures", () => {
    expect(cases.length).toBeGreaterThan(0);
  });

  for (const c of cases) {
    it(`replays ${c.name} identically`, () => {
      const st = newTextState();
      for (const rec of c.records) {
        applyTextOp(st, rec.op, rec.node_id, rec.hlc);
      }
      expect(textValue(st)).toBe(c.expected_value);

      const gotDelta = textDelta(st).map((d) => ({
        insert: d.insert,
        attributes: d.attributes ?? undefined,
      }));
      const wantDelta = (c.expected_delta ?? []).map((d) => ({
        insert: d.insert,
        attributes: d.attributes ?? undefined,
      }));
      expect(gotDelta).toEqual(wantDelta);
    });

    // NOTE: op application assumes causal delivery per origin (a delete/
    // format arrives after the insert it targets) — the same assumption
    // Yjs makes. Arbitrary-order convergence is provided by state merges
    // (mergeText), not op replay, so no reverse-order replay test here.
  }
});
