import 'dart:convert';

import 'package:grove_crdt/grove_crdt.dart';
import 'package:test/test.dart';

import 'support/fixture.dart';
import 'support/json_equivalent.dart';

typedef Json = Map<String, Object?>;

/// Decodes a JSON array of objects; `null` is an empty list, as Go writes a
/// nil slice.
List<Json> records(Object? raw) => ((raw as List<Object?>?) ?? const <Object?>[]).cast<Json>();

void applyRecords(TextState st, Object? raw) {
  for (final rec in records(raw)) {
    applyTextOp(st, TextOperation.fromJson(rec['op']), rec['node_id']! as String, HLC.fromJson(rec['hlc']));
  }
}

Object? stateJson(TextState st) => jsonDecode(encodeWire(st.toJson()));

void main() {
  // grove's own Go-generated fixture. The node platform has no dart:io, so the
  // path is read relative to the package root through readFixture.
  final cases = (jsonDecode(readFixture('../crdt/testdata/text_golden.json')) as List<Object?>).cast<Json>();

  group('Go/TS text golden parity', () {
    test('has fixtures', () {
      expect(cases, isNotEmpty);
    });

    for (final c in cases) {
      test('replays ${c['name']} identically', () {
        final st = newTextState();
        applyRecords(st, c['records']);
        expect(textValue(st), c['expected_value']);
        final got = [for (final d in textDelta(st)) d.toJson()];
        final want = [
          for (final d in records(c['expected_delta']))
            {
              'insert': d['insert'],
              if (d['attributes'] != null) 'attributes': d['attributes'],
            },
        ];
        expect(got, want);
      });
    }
  });

  // Generated by crdt-dart/tool/conformance_server/cmd/golden from the Go crdt
  // package. Every case puts astral characters (one rune, two UTF-16 units)
  // before the split points, so a port that counts UTF-16 units fails here.
  final astral = jsonDecode(readFixture('test/fixtures/text_astral_golden.json')) as Json;

  group('Go text golden parity with astral characters', () {
    final astralCases = records(astral['cases']);
    test('has fixtures', () {
      expect(astralCases, isNotEmpty);
      expect(
        astralCases.any((c) => (c['expected_value']! as String).runes.any((r) => r > 0xFFFF)),
        isTrue,
      );
    });

    for (final c in astralCases) {
      group('replays ${c['name']} identically', () {
        final st = newTextState();
        applyRecords(st, c['records']);

        test('value, length and delta', () {
          expect(textValue(st), c['expected_value']);
          expect(textLength(st), c['expected_len']);
          final want = [
            for (final d in records(c['expected_delta']))
              {'insert': d['insert'], if (d['attributes'] != null) 'attributes': d['attributes']},
          ];
          expect([for (final d in textDelta(st)) d.toJson()], want);
        });

        test('textRefAt gives the addresses Go gives', () {
          final want = records(c['ref_at']).map(TextRef.fromJson).toList();
          expect(want, hasLength(c['expected_len']! as int));
          for (var i = 0; i < want.length; i++) {
            expect(textRefAt(st, i), want[i], reason: 'index $i');
          }
          expect(textRefAt(st, want.length), isNull);
        });

        test('textIndexOf gives the indexes Go gives, deleted characters included', () {
          for (final e in records(c['index_of'])) {
            final ref = TextRef.fromJson(e['ref']);
            expect(textIndexOf(st, ref), e['index'], reason: '${ref.origin} @ ${ref.offset}');
          }
        });

        test('the stored fragments are the ones Go stores', () {
          final got = stateJson(st);
          expect(jsonEquivalent(c['final_state'], got), isTrue,
              reason: 'go:   ${jsonEncode(c['final_state'])}\ndart: ${jsonEncode(got)}');
        });
      });
    }
  });

  group('Go SetString parity with astral characters', () {
    for (final c in records(astral['set_string'])) {
      test('${c['name']} emits the ops Go emits', () {
        final st = newTextState();
        applyRecords(st, c['setup']);
        for (final step in records(c['steps'])) {
          final clocks = records(step['clocks']).map(HLC.fromJson).toList();
          var next = 0;
          final ops = textSetString(st, step['value']! as String, step['node_id']! as String, () => clocks[next++]);
          expect(next, clocks.length, reason: 'one clock per op for "${step['value']}"');
          final want = records(step['ops']);
          expect(ops, hasLength(want.length));
          for (var i = 0; i < ops.length; i++) {
            final got = jsonDecode(encodeWire(ops[i].toJson()));
            expect(jsonEquivalent(want[i], got), isTrue,
                reason: 'go:   ${jsonEncode(want[i])}\ndart: ${jsonEncode(got)}');
          }
          expect(textValue(st), step['value']);
        }
        expect(textValue(st), c['expected_value']);
        final got = stateJson(st);
        expect(jsonEquivalent(c['final_state'], got), isTrue,
            reason: 'go:   ${jsonEncode(c['final_state'])}\ndart: ${jsonEncode(got)}');
      });
    }
  });
}
