/**
 * Text CRDT — character-level collaborative text with formatting.
 *
 * Direct port of grove/crdt/text.go (origin-span fragments). See that file
 * for the model documentation. Every algorithm here must stay byte-
 * compatible with the Go implementation: the golden fixtures generated by
 * the Go test suite are replayed against this module in CI.
 */

import type {
  HLC,
  TextRef,
  TextSpan,
  TextFragment,
  TextState,
  TextOperation,
  TextDeltaSegment,
  AttrState,
} from "./types.js";
import { hlcAfter, hlcString, hlcTsString } from "./hlc.js";

const ZERO_HLC: HLC = { ts: 0, c: 0, node: "" };

/** Create an empty text state. */
export function newTextState(): TextState {
  return { frags: {} };
}

export function textOriginKey(h: HLC): string {
  return hlcString(h);
}

function isZeroHLC(h: HLC | undefined): boolean {
  return !h || (h.c === 0 && h.node === "" && hlcTsString(h.ts) === "0");
}

function isHeadRef(r: TextRef | undefined): boolean {
  return !r || isZeroHLC(r.origin);
}

function refKey(r: TextRef | undefined): string {
  if (isHeadRef(r)) return "@head";
  return textOriginKey(r!.origin) + "@" + r!.offset;
}

/** Rune-aware split (JS strings are UTF-16; Go offsets are runes). */
function runes(s: string): string[] {
  return Array.from(s);
}

function substringRunes(s: string, from: number, to: number): string {
  const rs = runes(s);
  return rs.slice(Math.max(0, from), Math.min(rs.length, to)).join("");
}

// --- Traversal ---

interface TextSeg {
  frag: TextFragment;
  from: number;
  to: number;
}

/** Document-order traversal over all addresses (including tombstones). */
export function textWalk(state: TextState): TextSeg[] {
  const children: Record<string, HLC[]> = {};
  const heads: Record<string, boolean> = {};

  for (const [key, frags] of Object.entries(state.frags)) {
    if (frags.length === 0 || frags[0].start !== 0) continue;
    heads[key] = true;
    const pk = refKey(frags[0].parent);
    (children[pk] ??= []).push(frags[0].origin);
  }
  for (const pk of Object.keys(children)) {
    children[pk].sort((a, b) => (hlcAfter(a, b) ? -1 : hlcAfter(b, a) ? 1 : 0));
  }

  const segs: TextSeg[] = [];
  const visited: Record<string, boolean> = {};

  const emitRange = (f: TextFragment, from: number, to: number) => {
    if (from < to) segs.push({ frag: f, from, to });
  };

  const emitOrigin = (origin: HLC) => {
    const key = textOriginKey(origin);
    if (visited[key]) return;
    visited[key] = true;

    const anchors: number[] = [];
    const prefix = key + "@";
    for (const pk of Object.keys(children)) {
      if (pk.startsWith(prefix)) {
        const off = Number(pk.slice(prefix.length));
        if (Number.isFinite(off)) anchors.push(off);
      }
    }
    anchors.sort((a, b) => a - b);

    const emitChildren = (offset: number) => {
      const kids = children[refKey({ origin, offset })] ?? [];
      for (const child of kids) emitOrigin(child);
    };

    let ai = 0;
    for (const f of state.frags[key] ?? []) {
      let cur = f.start;
      const end = f.start + f.length;
      while (ai < anchors.length && anchors[ai] < end) {
        const k = anchors[ai];
        if (k < cur) {
          emitChildren(k);
          ai++;
          continue;
        }
        emitRange(f, cur - f.start, k + 1 - f.start);
        emitChildren(k);
        cur = k + 1;
        ai++;
      }
      emitRange(f, cur - f.start, end - f.start);
    }
    for (; ai < anchors.length; ai++) emitChildren(anchors[ai]);
  };

  for (const root of children["@head"] ?? []) emitOrigin(root);

  const orphans: HLC[] = [];
  for (const [key, frags] of Object.entries(state.frags)) {
    if (heads[key] && !visited[key]) orphans.push(frags[0].origin);
  }
  orphans.sort((a, b) => (hlcAfter(a, b) ? -1 : hlcAfter(b, a) ? 1 : 0));
  for (const o of orphans) emitOrigin(o);

  return segs;
}

// --- Reads ---

function segVisible(seg: TextSeg): boolean {
  return !seg.frag.tombstone && seg.frag.content !== "";
}

/** Visible text. */
export function textValue(state: TextState): string {
  let out = "";
  for (const seg of textWalk(state)) {
    if (!segVisible(seg)) continue;
    out += substringRunes(seg.frag.content, seg.from, seg.to);
  }
  return out;
}

/** Number of visible characters (runes). */
export function textLength(state: TextState): number {
  let n = 0;
  for (const seg of textWalk(state)) {
    if (!segVisible(seg)) continue;
    n += seg.to - seg.from;
  }
  return n;
}

function resolvedAttrs(
  attrs: Record<string, AttrState> | undefined
): Record<string, unknown> | undefined {
  if (!attrs) return undefined;
  let out: Record<string, unknown> | undefined;
  for (const [k, a] of Object.entries(attrs)) {
    if (a.value === null || a.value === undefined) continue;
    (out ??= {})[k] = a.value;
  }
  return out;
}

function attrsEqual(
  a: Record<string, unknown> | undefined,
  b: Record<string, unknown> | undefined
): boolean {
  const ka = Object.keys(a ?? {});
  const kb = Object.keys(b ?? {});
  if (ka.length !== kb.length) return false;
  return ka.every((k) => JSON.stringify(a![k]) === JSON.stringify(b![k]));
}

/** Quill-style attribute-run segments of the visible text. */
export function textDelta(state: TextState): TextDeltaSegment[] {
  const out: TextDeltaSegment[] = [];
  for (const seg of textWalk(state)) {
    if (!segVisible(seg)) continue;
    const attrs = resolvedAttrs(seg.frag.attrs);
    const content = substringRunes(seg.frag.content, seg.from, seg.to);
    const last = out[out.length - 1];
    if (last && attrsEqual(last.attributes, attrs)) {
      last.insert += content;
      continue;
    }
    const segment: TextDeltaSegment = { insert: content };
    if (attrs) segment.attributes = attrs;
    out.push(segment);
  }
  return out;
}

/** Stable address of the index-th visible character. */
export function textRefAt(state: TextState, index: number): TextRef | null {
  if (index < 0) return null;
  let n = 0;
  for (const seg of textWalk(state)) {
    if (!segVisible(seg)) continue;
    const width = seg.to - seg.from;
    if (index < n + width) {
      return {
        origin: seg.frag.origin,
        offset: seg.frag.start + seg.from + (index - n),
      };
    }
    n += width;
  }
  return null;
}

/**
 * Current visible index of the character at ref. Tombstoned characters
 * collapse to the position they would occupy (cursor semantics).
 */
export function textIndexOf(state: TextState, ref: TextRef): number | null {
  if (isHeadRef(ref)) return 0;
  let n = 0;
  for (const seg of textWalk(state)) {
    const covers =
      textOriginKey(seg.frag.origin) === textOriginKey(ref.origin) &&
      ref.offset >= seg.frag.start + seg.from &&
      ref.offset < seg.frag.start + seg.to;
    const visible = segVisible(seg);
    if (covers) {
      if (visible) return n + (ref.offset - seg.frag.start - seg.from);
      return n;
    }
    if (visible) n += seg.to - seg.from;
  }
  return null;
}

// --- Mutation (op application) ---

function coverage(state: TextState, key: string): number {
  const frags = state.frags[key];
  if (!frags || frags.length === 0) return 0;
  const last = frags[frags.length - 1];
  return last.start + last.length;
}

function cloneAttrState(
  attrs: Record<string, AttrState> | undefined
): Record<string, AttrState> | undefined {
  if (!attrs) return undefined;
  return { ...attrs };
}

/** Ensure a fragment boundary exists at address `at` in the origin. */
function splitAt(state: TextState, key: string, at: number): void {
  const frags = state.frags[key];
  if (!frags) return;
  for (let i = 0; i < frags.length; i++) {
    const f = frags[i];
    if (at <= f.start || at >= f.start + f.length) continue;
    const cut = at - f.start;
    const head: TextFragment = { ...f, length: cut, attrs: cloneAttrState(f.attrs) };
    const tail: TextFragment = {
      ...f,
      start: at,
      length: f.length - cut,
      attrs: cloneAttrState(f.attrs),
    };
    delete tail.parent;
    if (f.content !== "") {
      head.content = substringRunes(f.content, 0, cut);
      tail.content = substringRunes(f.content, cut, f.length);
    }
    frags.splice(i, 1, head, tail);
    return;
  }
}

function applySpans(
  state: TextState,
  spans: TextSpan[] | undefined,
  fn: (f: TextFragment) => void
): void {
  for (const span of spans ?? []) {
    const key = textOriginKey(span.origin);
    splitAt(state, key, span.start);
    splitAt(state, key, span.start + span.length);
    for (const f of state.frags[key] ?? []) {
      if (f.start >= span.start && f.start + f.length <= span.start + span.length) {
        fn(f);
      }
    }
  }
}

/**
 * Fold one TextOperation into the state. Deterministic and
 * order-independent; duplicate inserts are ignored (idempotent).
 * Mirrors Go TextState.Apply.
 */
export function applyTextOp(
  state: TextState,
  op: TextOperation,
  nodeID: string,
  clock: HLC
): void {
  switch (op.op) {
    case "insert": {
      if (!op.content) return;
      const origin = isZeroHLC(op.origin) ? clock : op.origin!;
      const key = textOriginKey(origin);
      let start = 0;
      let parent = op.ref;
      if (op.ref && !isHeadRef(op.ref) && textOriginKey(op.ref.origin) === key) {
        start = op.ref.offset + 1;
        parent = undefined;
      }
      const length = runes(op.content).length;
      const frags = (state.frags[key] ??= []);
      // Idempotence: skip if any part of the range already exists.
      for (const f of frags) {
        if (f.start < start + length && start < f.start + f.length) return;
      }
      const frag: TextFragment = {
        origin,
        start,
        content: op.content,
        length,
      };
      if (parent && !isHeadRef(parent)) frag.parent = parent;
      else if (start === 0) frag.parent = parent ?? { origin: ZERO_HLC, offset: 0 };
      if (op.attrs && Object.keys(op.attrs).length > 0) {
        frag.attrs = {};
        for (const [k, v] of Object.entries(op.attrs)) {
          frag.attrs[k] = { value: v, hlc: clock, node_id: nodeID };
        }
      }
      // Coalesce with the preceding tail fragment when storage-compatible.
      const last = frags[frags.length - 1];
      if (
        last &&
        start > 0 &&
        last.start + last.length === start &&
        !last.tombstone &&
        !last.attrs &&
        !frag.attrs &&
        last.content !== ""
      ) {
        last.content += op.content;
        last.length += length;
        return;
      }
      frags.push(frag);
      frags.sort((a, b) => a.start - b.start);
      return;
    }

    case "delete":
      applySpans(state, op.spans, (f) => {
        f.tombstone = true;
      });
      return;

    case "format":
      applySpans(state, op.spans, (f) => {
        f.attrs ??= {};
        for (const [k, v] of Object.entries(op.attrs ?? {})) {
          const existing = f.attrs[k];
          if (existing && !hlcAfter(clock, existing.hlc)) continue;
          f.attrs[k] = { value: v, hlc: clock, node_id: nodeID };
        }
      });
      return;

    default:
      throw new Error(`crdt: unknown text op ${String(op.op)}`);
  }
}

// --- Local edit API (mutates state AND returns the wire op) ---

/** Resolve `length` visible chars starting at ref's char into spans. */
export function resolveTextSpans(
  state: TextState,
  ref: TextRef | null,
  length: number
): TextSpan[] {
  if (length <= 0) throw new Error("crdt: text span length must be positive");
  const start = ref === null ? 0 : textIndexOf(state, ref);
  if (start === null) throw new Error("crdt: text ref not found");

  const spans: TextSpan[] = [];
  let n = 0;
  let remaining = length;
  for (const seg of textWalk(state)) {
    if (remaining === 0) break;
    if (!segVisible(seg)) continue;
    const width = seg.to - seg.from;
    if (start >= n + width) {
      n += width;
      continue;
    }
    const from = start > n ? start - n : 0;
    const take = Math.min(width - from, remaining);
    spans.push({
      origin: seg.frag.origin,
      start: seg.frag.start + seg.from + from,
      length: take,
    });
    remaining -= take;
    n += width;
  }
  if (remaining > 0) {
    throw new Error(`crdt: text span exceeds document (${remaining} chars short)`);
  }
  // Merge adjacent spans.
  const out: TextSpan[] = [];
  for (const s of spans) {
    const last = out[out.length - 1];
    if (
      last &&
      textOriginKey(last.origin) === textOriginKey(s.origin) &&
      s.start === last.start + last.length
    ) {
      last.length += s.length;
      continue;
    }
    out.push(s);
  }
  return out;
}

/** Insert content after ref (null/zero ref = document head). */
export function textInsert(
  state: TextState,
  ref: TextRef | null,
  content: string,
  nodeID: string,
  clock: HLC
): TextOperation {
  if (!content) throw new Error("crdt: empty text insert");
  const anchor: TextRef = ref ?? { origin: ZERO_HLC, offset: 0 };
  const op: TextOperation = { op: "insert", ref: anchor, content, origin: clock };
  if (!isHeadRef(anchor) && anchor.origin.node === nodeID) {
    const cover = coverage(state, textOriginKey(anchor.origin));
    if (cover > 0 && anchor.offset === cover - 1) {
      op.origin = anchor.origin;
    }
  }
  applyTextOp(state, op, nodeID, clock);
  return op;
}

/** Tombstone `length` visible chars starting at ref's char. */
export function textDeleteOp(
  state: TextState,
  ref: TextRef | null,
  length: number
): TextOperation {
  const spans = resolveTextSpans(state, ref, length);
  const op: TextOperation = { op: "delete", spans };
  applyTextOp(state, op, "", ZERO_HLC);
  return op;
}

/** Apply formatting attributes to `length` visible chars from ref. */
export function textFormat(
  state: TextState,
  ref: TextRef | null,
  length: number,
  attrs: Record<string, unknown>,
  nodeID: string,
  clock: HLC
): TextOperation {
  if (!attrs || Object.keys(attrs).length === 0) {
    throw new Error("crdt: format without attrs");
  }
  const spans = resolveTextSpans(state, ref, length);
  const op: TextOperation = { op: "format", spans, attrs };
  applyTextOp(state, op, nodeID, clock);
  return op;
}

// --- State-based merge (mirrors Go MergeText) ---

function subFragment(f: TextFragment, from: number, to: number): TextFragment {
  const cp: TextFragment = { ...f, start: from, length: to - from };
  if (f.content !== "") {
    cp.content = substringRunes(f.content, from - f.start, to - f.start);
  }
  if (from !== f.start) delete cp.parent;
  if (f.attrs) cp.attrs = { ...f.attrs };
  return cp;
}

function normalizeFrags(
  frags: TextFragment[],
  cuts: number[]
): Map<number, TextFragment> {
  const out = new Map<number, TextFragment>();
  for (const f of frags) {
    const end = f.start + f.length;
    let prev = f.start;
    for (const c of cuts) {
      if (c <= prev || c >= end) continue;
      out.set(prev, subFragment(f, prev, c));
      prev = c;
    }
    out.set(prev, subFragment(f, prev, end));
  }
  return out;
}

function combineFrags(a: TextFragment, b: TextFragment): TextFragment {
  const out: TextFragment = { ...a };
  out.tombstone = Boolean(a.tombstone || b.tombstone);
  if (!out.tombstone) delete out.tombstone;
  if (out.content === "") out.content = b.content;
  if (!out.parent && b.parent) out.parent = b.parent;
  if (!a.attrs && !b.attrs) {
    delete out.attrs;
    return out;
  }
  const attrs: Record<string, AttrState> = { ...(a.attrs ?? {}) };
  for (const [k, v] of Object.entries(b.attrs ?? {})) {
    const existing = attrs[k];
    if (!existing || hlcAfter(v.hlc, existing.hlc)) attrs[k] = v;
  }
  out.attrs = attrs;
  return out;
}

function mergeOriginFrags(
  a: TextFragment[] | undefined,
  b: TextFragment[] | undefined
): TextFragment[] {
  if (!a || a.length === 0) return (b ?? []).map((f) => subFragment(f, f.start, f.start + f.length));
  if (!b || b.length === 0) return a.map((f) => subFragment(f, f.start, f.start + f.length));

  const bounds = new Set<number>();
  for (const f of [...a, ...b]) {
    bounds.add(f.start);
    bounds.add(f.start + f.length);
  }
  const cuts = [...bounds].sort((x, y) => x - y);

  const na = normalizeFrags(a, cuts);
  const nb = normalizeFrags(b, cuts);

  const starts = [...new Set([...na.keys(), ...nb.keys()])].sort((x, y) => x - y);
  const out: TextFragment[] = [];
  for (const s of starts) {
    const fa = na.get(s);
    const fb = nb.get(s);
    if (!fa) out.push(fb!);
    else if (!fb) out.push(fa);
    else out.push(combineFrags(fa, fb));
  }
  return out;
}

/** Merge two text states. Commutative, associative, idempotent. */
export function mergeText(
  local: TextState | null | undefined,
  remote: TextState | null | undefined
): TextState {
  if (!local) return remote ?? newTextState();
  if (!remote) return local;
  const merged = newTextState();
  const keys = new Set([...Object.keys(local.frags), ...Object.keys(remote.frags)]);
  for (const k of keys) {
    merged.frags[k] = mergeOriginFrags(local.frags[k], remote.frags[k]);
  }
  return merged;
}
