/// Text CRDT: character-level collaborative text with formatting.
///
/// A port of `crdt-js/src/text.ts`, which is itself a port of `crdt/text.go`
/// (origin-span fragments). See that file for the model documentation. Where
/// the two disagree this port follows Go, because the Go server is the
/// authority. Every algorithm here must stay compatible with the Go
/// implementation: the golden fixtures generated by Go are replayed against
/// this module in the tests.
///
/// Every offset, start and length counts runes (Unicode code points), as Go
/// does. A Dart string is UTF-16, so content is only ever indexed through
/// `String.runes` and rebuilt with `String.fromCharCodes`. An astral character
/// is one offset, and an unpaired surrogate is one offset too, as Go decodes
/// it to a single U+FFFD.
library;

import 'hlc.dart';
import 'types.dart';

/// One Quill-style segment of the visible text: a run of characters that share
/// the same formatting attributes.
final class TextDeltaSegment {
  /// Creates a segment. [attributes] is `null` for unformatted text.
  const TextDeltaSegment(this.insert, {this.attributes});

  /// The text of the run.
  final String insert;

  /// The resolved formatting attributes, or `null` when there are none.
  final Map<String, Object?>? attributes;

  /// The Go `TextDelta` wire form: `attributes` is written only when non-empty.
  Map<String, Object?> toJson() {
    final attrs = attributes;
    return {
      'insert': insert,
      if (attrs != null && attrs.isNotEmpty) 'attributes': attrs,
    };
  }

  @override
  String toString() => 'TextDeltaSegment(${toJson()})';
}

/// One traversal step: the address range `[from, to)` of [frag], counted in
/// runes from the start of the fragment.
final class TextSeg {
  /// Creates a traversal step.
  const TextSeg(this.frag, this.from, this.to);

  /// The fragment the range belongs to.
  final TextFragment frag;

  /// The first rune of the range, relative to the fragment start.
  final int from;

  /// One past the last rune of the range, relative to the fragment start.
  final int to;
}

/// Creates an empty text state.
TextState newTextState() => TextState();

/// The key under which fragments of the origin [h] are stored.
String textOriginKey(HLC h) => hlcString(h);

bool _isHeadRef(TextRef? r) => r == null || r.origin.isZero;

String _refKey(TextRef r) {
  if (_isHeadRef(r)) return '@head';
  return '${textOriginKey(r.origin)}@${r.offset}';
}

int _runeCount(String s) => s.runes.length;

/// The runes `[from, to)` of [s], clamped to the string, as Go `substring`.
String _substringRunes(String s, int from, int to) {
  final rs = s.runes.toList();
  final a = from < 0 ? 0 : from;
  final b = to > rs.length ? rs.length : to;
  if (a >= b) return '';
  return String.fromCharCodes(rs.sublist(a, b));
}

// --- Traversal ---

/// Document-order traversal over all addresses, tombstones included.
///
/// Iterative: an explicit stack stands in for the recursion Go and TypeScript
/// use, so a long chain of origins each anchored in the previous one cannot
/// overflow the call stack.
List<TextSeg> textWalk(TextState state) {
  // children: parent ref key -> child origins, newest first.
  final children = <String, List<HLC>>{};
  // anchors: origin key -> offsets that have children, found while building
  // children so each origin does not rescan every parent key.
  final anchorsByOrigin = <String, List<int>>{};
  final heads = <String>{};

  for (final entry in state.frags.entries) {
    final frags = entry.value;
    if (frags.isEmpty || frags[0].start != 0) continue;
    heads.add(entry.key);
    final head = frags[0];
    final pk = _refKey(head.parent);
    final list = children[pk];
    if (list == null) {
      children[pk] = [head.origin];
      if (!_isHeadRef(head.parent)) {
        (anchorsByOrigin[textOriginKey(head.parent.origin)] ??= <int>[]).add(head.parent.offset);
      }
    } else {
      list.add(head.origin);
    }
  }
  for (final list in children.values) {
    list.sort((a, b) => b.compareTo(a));
  }

  final segs = <TextSeg>[];
  final visited = <String>{};
  // Holds origins still to emit (HLC) and ranges ready to output (TextSeg).
  final stack = <Object>[];

  void expand(HLC origin) {
    final key = textOriginKey(origin);
    if (!visited.add(key)) return;

    final anchors = List<int>.of(anchorsByOrigin[key] ?? const <int>[])..sort();
    final acts = <Object>[];

    void emitRange(TextFragment f, int from, int to) {
      if (from < to) acts.add(TextSeg(f, from, to));
    }

    void emitChildren(int offset) {
      final kids = children[_refKey(TextRef(origin, offset))];
      if (kids != null) acts.addAll(kids);
    }

    var ai = 0;
    for (final f in state.frags[key] ?? const <TextFragment>[]) {
      var cur = f.start;
      final end = f.start + f.length;
      while (ai < anchors.length && anchors[ai] < end) {
        final k = anchors[ai];
        if (k < cur) {
          // Anchor in a hole before this fragment: the anchor character has
          // not arrived, so emit the children where it will appear.
          emitChildren(k);
          ai++;
          continue;
        }
        emitRange(f, cur - f.start, k + 1 - f.start);
        emitChildren(k);
        cur = k + 1;
        ai++;
      }
      emitRange(f, cur - f.start, end - f.start);
    }
    // Children anchored past the current coverage.
    for (; ai < anchors.length; ai++) {
      emitChildren(anchors[ai]);
    }
    for (var i = acts.length - 1; i >= 0; i--) {
      stack.add(acts[i]);
    }
  }

  void drain() {
    while (stack.isNotEmpty) {
      final item = stack.removeLast();
      if (item is TextSeg) {
        segs.add(item);
      } else {
        expand(item as HLC);
      }
    }
  }

  void pushAll(List<HLC> origins) {
    for (var i = origins.length - 1; i >= 0; i--) {
      stack.add(origins[i]);
    }
  }

  pushAll(children['@head'] ?? const <HLC>[]);
  drain();

  // Deterministic placement for origins whose anchors are unreachable (the
  // parent origin's head is missing): append them newest first.
  final orphans = <HLC>[
    for (final e in state.frags.entries)
      if (heads.contains(e.key) && !visited.contains(e.key)) e.value[0].origin,
  ]..sort((a, b) => b.compareTo(a));
  pushAll(orphans);
  drain();

  return segs;
}

// --- Reads ---

bool _segVisible(TextSeg seg) => !seg.frag.tombstone && seg.frag.content.isNotEmpty;

/// The visible text.
String textValue(TextState state) {
  final out = StringBuffer();
  for (final seg in textWalk(state)) {
    if (!_segVisible(seg)) continue;
    out.write(_substringRunes(seg.frag.content, seg.from, seg.to));
  }
  return out.toString();
}

/// The number of visible characters (runes).
int textLength(TextState state) {
  var n = 0;
  for (final seg in textWalk(state)) {
    if (!_segVisible(seg)) continue;
    n += seg.to - seg.from;
  }
  return n;
}

Map<String, Object?>? _resolvedAttrs(Map<String, AttrState> attrs) {
  Map<String, Object?>? out;
  for (final e in attrs.entries) {
    final v = e.value.value.value;
    if (v == null) continue;
    (out ??= <String, Object?>{})[e.key] = v;
  }
  return out;
}

bool _attrsEqual(Map<String, Object?>? a, Map<String, Object?>? b) {
  final ma = a ?? const <String, Object?>{};
  final mb = b ?? const <String, Object?>{};
  if (ma.length != mb.length) return false;
  for (final e in ma.entries) {
    if (!mb.containsKey(e.key)) return false;
    if (JsonValue(e.value) != JsonValue(mb[e.key])) return false;
  }
  return true;
}

/// The visible text as Quill-style attribute-run segments. Adjacent runs with
/// identical attributes are merged.
List<TextDeltaSegment> textDelta(TextState state) {
  final texts = <StringBuffer>[];
  final attrsOf = <Map<String, Object?>?>[];
  for (final seg in textWalk(state)) {
    if (!_segVisible(seg)) continue;
    final attrs = _resolvedAttrs(seg.frag.attrs);
    final content = _substringRunes(seg.frag.content, seg.from, seg.to);
    if (texts.isNotEmpty && _attrsEqual(attrsOf.last, attrs)) {
      texts.last.write(content);
      continue;
    }
    texts.add(StringBuffer(content));
    attrsOf.add(attrs);
  }
  return [
    for (var i = 0; i < texts.length; i++) TextDeltaSegment(texts[i].toString(), attributes: attrsOf[i]),
  ];
}

/// The stable address of the visible character at [index], or `null` when
/// [index] is outside the text.
TextRef? textRefAt(TextState state, int index) {
  if (index < 0) return null;
  var n = 0;
  for (final seg in textWalk(state)) {
    if (!_segVisible(seg)) continue;
    final width = seg.to - seg.from;
    if (index < n + width) {
      return TextRef(seg.frag.origin, seg.frag.start + seg.from + (index - n));
    }
    n += width;
  }
  return null;
}

/// The current visible index of the character at [ref], or `null` when the
/// address is unknown. A tombstoned character collapses to the index it would
/// occupy (the position of the next visible character), which is cursor
/// semantics.
int? textIndexOf(TextState state, TextRef ref) {
  if (_isHeadRef(ref)) return 0;
  var n = 0;
  for (final seg in textWalk(state)) {
    final covers = seg.frag.origin == ref.origin &&
        ref.offset >= seg.frag.start + seg.from &&
        ref.offset < seg.frag.start + seg.to;
    final visible = _segVisible(seg);
    if (covers) {
      if (visible) return n + (ref.offset - seg.frag.start - seg.from);
      return n;
    }
    if (visible) n += seg.to - seg.from;
  }
  return null;
}

// --- Mutation (op application) ---

/// The exclusive upper address bound stored for an origin.
int _coverage(TextState state, String key) {
  final frags = state.frags[key];
  if (frags == null || frags.isEmpty) return 0;
  final last = frags.last;
  return last.start + last.length;
}

/// Ensures a fragment boundary exists at address [at] in the origin [key].
void _splitAt(TextState state, String key, int at) {
  final frags = state.frags[key];
  if (frags == null) return;
  for (var i = 0; i < frags.length; i++) {
    final f = frags[i];
    if (at <= f.start || at >= f.start + f.length) continue;
    final cut = at - f.start;
    final head = f.clone()..length = cut;
    final tail = f.clone()
      ..start = at
      ..length = f.length - cut
      ..parent = TextRef.head;
    if (f.content.isNotEmpty) {
      head.content = _substringRunes(f.content, 0, cut);
      tail.content = _substringRunes(f.content, cut, f.length);
    }
    frags.replaceRange(i, i + 1, [head, tail]);
    return;
  }
}

/// Splits fragments at every span boundary and applies [fn] to the fragments
/// fully covered by each span.
void _applySpans(TextState state, List<TextSpan> spans, void Function(TextFragment) fn) {
  for (final span in spans) {
    final key = textOriginKey(span.origin);
    _splitAt(state, key, span.start);
    _splitAt(state, key, span.start + span.length);
    for (final f in state.frags[key] ?? const <TextFragment>[]) {
      if (f.start >= span.start && f.start + f.length <= span.start + span.length) {
        fn(f);
      }
    }
  }
}

bool _isHighSurrogate(int unit) => unit >= 0xD800 && unit <= 0xDBFF;

bool _isLowSurrogate(int unit) => unit >= 0xDC00 && unit <= 0xDFFF;

/// Folds one [TextOperation] into [s]. Inserts are idempotent: a duplicate
/// delivery is ignored. Delete and format ops touch the exact spans they name
/// and assume causal delivery per origin, so they must arrive after the insert
/// whose addresses they reference. Mirrors Go `TextState.Apply`.
///
/// Mutates [s]; use [applyTextOpTo] to leave the input untouched.
///
/// Throws a [StateError] for an insert without content, as Go returns an
/// error.
void applyTextOp(TextState s, TextOperation op, String nodeId, HLC clock) {
  switch (op.op) {
    case TextOpType.insert:
      _applyInsert(s, op, nodeId, clock);
    case TextOpType.delete:
      _applySpans(s, op.spans, (f) => f.tombstone = true);
    case TextOpType.format:
      _applySpans(s, op.spans, (f) {
        for (final e in op.attrs.entries) {
          final existing = f.attrs[e.key];
          if (existing != null && !clock.isAfter(existing.hlc)) continue;
          f.attrs[e.key] = AttrState(e.value, clock, nodeId);
        }
      });
  }
}

void _applyInsert(TextState s, TextOperation op, String nodeId, HLC clock) {
  if (op.content.isEmpty) {
    throw StateError('crdt: text insert without content');
  }
  final origin = op.origin.isZero ? clock : op.origin;
  final key = textOriginKey(origin);
  var start = 0;
  var parent = op.ref;
  if (origin == op.ref.origin) {
    // Span extension: the content continues the ref'd origin.
    start = op.ref.offset + 1;
    parent = TextRef.head;
  }

  final length = _runeCount(op.content);
  final frags = s.frags.putIfAbsent(key, () => <TextFragment>[]);
  // Idempotence: skip if any part of [start, start + length) already exists.
  for (final f in frags) {
    if (f.start < start + length && start < f.start + f.length) return;
  }

  final frag = TextFragment(
    origin: origin,
    start: start,
    content: op.content,
    length: length,
    parent: parent,
    attrs: {
      for (final e in op.attrs.entries) e.key: AttrState(e.value, clock, nodeId),
    },
  );

  // Coalesce with the preceding tail fragment when storage-compatible. Joining
  // a trailing high surrogate to a leading low surrogate would fuse two
  // unpaired surrogates into one astral character and put the fragment's rune
  // length out of step with its content, so that case stays a separate
  // fragment.
  if (frags.isNotEmpty && start > 0) {
    final tail = frags.last;
    if (tail.start + tail.length == start &&
        !tail.tombstone &&
        tail.attrs.isEmpty &&
        frag.attrs.isEmpty &&
        tail.content.isNotEmpty &&
        !(_isHighSurrogate(tail.content.codeUnits.last) && _isLowSurrogate(op.content.codeUnitAt(0)))) {
      tail.content += op.content;
      tail.length += length;
      return;
    }
  }
  frags
    ..add(frag)
    ..sort((a, b) => a.start.compareTo(b.start));
}

/// Folds [op] into a copy of [s] and returns the copy, leaving [s] untouched.
TextState applyTextOpTo(TextState s, TextOperation op, String nodeId, HLC clock) {
  final next = cloneTextState(s);
  applyTextOp(next, op, nodeId, clock);
  return next;
}

/// A deep copy of [s], so a mutating applier cannot touch the input.
TextState cloneTextState(TextState s) => s.clone();

// --- Local edit API (mutates state AND returns the wire op) ---

/// Resolves [length] visible characters starting at [ref]'s character into
/// explicit address spans. A `null` [ref] is the document head.
///
/// Throws an [ArgumentError] when [length] is not positive and a [StateError]
/// when [ref] is unknown or the span runs past the end of the text.
List<TextSpan> resolveTextSpans(TextState s, TextRef? ref, int length) {
  if (length <= 0) {
    throw ArgumentError.value(length, 'length', 'crdt: text span length must be positive');
  }
  final start = ref == null ? 0 : textIndexOf(s, ref);
  if (start == null) {
    throw StateError('crdt: text ref ${textOriginKey(ref!.origin)}+${ref.offset} not found');
  }

  final spans = <TextSpan>[];
  var n = 0;
  var remaining = length;
  for (final seg in textWalk(s)) {
    if (remaining == 0) break;
    if (!_segVisible(seg)) continue;
    final width = seg.to - seg.from;
    if (start >= n + width) {
      n += width;
      continue;
    }
    final from = start > n ? start - n : 0;
    final take = width - from < remaining ? width - from : remaining;
    spans.add(TextSpan(seg.frag.origin, seg.frag.start + seg.from + from, take));
    remaining -= take;
    n += width;
  }
  if (remaining > 0) {
    throw StateError('crdt: text span exceeds document ($remaining chars short)');
  }
  // Merge adjacent spans.
  final out = <TextSpan>[];
  for (final sp in spans) {
    if (out.isNotEmpty && out.last.origin == sp.origin && sp.start == out.last.start + out.last.length) {
      final last = out.removeLast();
      out.add(TextSpan(last.origin, last.start, last.length + sp.length));
      continue;
    }
    out.add(sp);
  }
  return out;
}

/// Inserts [content] after [ref] (a `null` or zero ref is the document head),
/// applies the insert to [s] and returns the wire op.
///
/// Sequential inserts by the same node at the tail of its own span extend that
/// span, so typing coalesces into one origin. Throws an [ArgumentError] for
/// empty content.
TextOperation textInsert(TextState s, TextRef? ref, String content, String nodeId, HLC clock) {
  if (content.isEmpty) {
    throw ArgumentError.value(content, 'content', 'crdt: empty text insert');
  }
  final anchor = ref ?? TextRef.head;
  var origin = clock;
  if (!_isHeadRef(anchor) && anchor.origin.node == nodeId) {
    final cover = _coverage(s, textOriginKey(anchor.origin));
    if (cover > 0 && anchor.offset == cover - 1) {
      origin = anchor.origin;
    }
  }
  final op = TextOperation(TextOpType.insert, ref: anchor, content: content, origin: origin);
  applyTextOp(s, op, nodeId, clock);
  return op;
}

/// Tombstones [length] visible characters starting at [ref]'s character,
/// applies the delete to [s] and returns the wire op with the exact spans it
/// resolved.
TextOperation textDeleteOp(TextState s, TextRef? ref, int length) {
  final spans = resolveTextSpans(s, ref, length);
  final op = TextOperation(TextOpType.delete, spans: spans);
  applyTextOp(s, op, '', HLC.zero);
  return op;
}

/// Applies the formatting [attrs] to [length] visible characters from [ref],
/// applies the format to [s] and returns the wire op. A `null` value clears
/// the attribute and is kept as an LWW tombstone.
///
/// Throws an [ArgumentError] when [attrs] is empty.
TextOperation textFormat(
  TextState s,
  TextRef? ref,
  int length,
  Map<String, Object?> attrs,
  String nodeId,
  HLC clock,
) {
  if (attrs.isEmpty) {
    throw ArgumentError.value(attrs, 'attrs', 'crdt: format without attrs');
  }
  final spans = resolveTextSpans(s, ref, length);
  final op = TextOperation(
    TextOpType.format,
    spans: spans,
    attrs: {for (final e in attrs.entries) e.key: JsonValue(e.value)},
  );
  applyTextOp(s, op, nodeId, clock);
  return op;
}

// --- State-based merge (mirrors Go MergeText) ---

/// The `[from, to)` address slice of [f].
TextFragment _subFragment(TextFragment f, int from, int to) {
  final cp = f.clone()
    ..start = from
    ..length = to - from;
  if (f.content.isNotEmpty) {
    cp.content = _substringRunes(f.content, from - f.start, to - f.start);
  }
  if (from != f.start) cp.parent = TextRef.head;
  return cp;
}

/// Splits copies of [frags] at every cut point, keyed by start.
Map<int, TextFragment> _normalizeFrags(List<TextFragment> frags, List<int> cuts) {
  final out = <int, TextFragment>{};
  for (final f in frags) {
    final end = f.start + f.length;
    var prev = f.start;
    for (final c in cuts) {
      if (c <= prev || c >= end) continue;
      out[prev] = _subFragment(f, prev, c);
      prev = c;
    }
    out[prev] = _subFragment(f, prev, end);
  }
  return out;
}

/// Merges two aligned fragments (same origin, start and length).
TextFragment _combineFrags(TextFragment a, TextFragment b) {
  final out = a.clone();
  out.tombstone = a.tombstone || b.tombstone;
  if (out.content.isEmpty) out.content = b.content;
  if (_isHeadRef(out.parent) && !_isHeadRef(b.parent)) out.parent = b.parent;
  if (a.attrs.isEmpty && b.attrs.isEmpty) {
    out.attrs = <String, AttrState>{};
    return out;
  }
  final attrs = Map<String, AttrState>.of(a.attrs);
  for (final e in b.attrs.entries) {
    final existing = attrs[e.key];
    if (existing == null || e.value.hlc.isAfter(existing.hlc)) attrs[e.key] = e.value;
  }
  out.attrs = attrs;
  return out;
}

List<TextFragment> _mergeOriginFrags(List<TextFragment>? a, List<TextFragment>? b) {
  if (a == null || a.isEmpty) return [for (final f in b ?? const <TextFragment>[]) f.clone()];
  if (b == null || b.isEmpty) return [for (final f in a) f.clone()];

  // Finest common partition: every boundary from both sides.
  final bounds = <int>{};
  for (final f in [...a, ...b]) {
    bounds
      ..add(f.start)
      ..add(f.start + f.length);
  }
  final cuts = bounds.toList()..sort();

  final na = _normalizeFrags(a, cuts);
  final nb = _normalizeFrags(b, cuts);

  final starts = {...na.keys, ...nb.keys}.toList()..sort();
  final out = <TextFragment>[];
  for (final s in starts) {
    final fa = na[s];
    final fb = nb[s];
    if (fa == null) {
      out.add(fb!);
    } else if (fb == null) {
      out.add(fa);
    } else {
      out.add(_combineFrags(fa, fb));
    }
  }
  return out;
}

/// Merges two text states: a per-origin union with both sides normalised to the
/// finest common fragment partition, then a per-fragment tombstone OR and a
/// per-attribute last-writer-wins. Commutative, associative and idempotent.
///
/// Neither input is mutated. When one side is `null` the other side itself is
/// returned (an empty state when both are), so do not mutate the result in
/// place if an input is still in use; use [applyTextOpTo].
TextState mergeText(TextState? local, TextState? remote) {
  if (local == null) return remote ?? newTextState();
  if (remote == null) return local;
  final merged = newTextState();
  final keys = {...local.frags.keys, ...remote.frags.keys};
  for (final k in keys) {
    merged.frags[k] = _mergeOriginFrags(local.frags[k], remote.frags[k]);
  }
  return merged;
}

// --- Whole-string writes ---

/// The visible runes of [s], collected segment by segment so the count always
/// agrees with [textLength] and [textRefAt].
List<int> _visibleRunes(TextState s) {
  final out = <int>[];
  for (final seg in textWalk(s)) {
    if (!_segVisible(seg)) continue;
    out.addAll(_substringRunes(seg.frag.content, seg.from, seg.to).runes);
  }
  return out;
}

/// Reconciles [s] toward [value] with a common prefix and suffix diff and
/// returns the ops it applied, in order. Port of Go `TextState.SetString`.
///
/// Each op is applied to [s] before this returns, and [nextClock] is called
/// once per emitted op (a delete first, then an insert), so the caller wraps
/// each op in a change record with the clock it was given. A delete carries no
/// clock of its own, so the insert's clock is the one that stamps the new
/// origin.
///
/// Throws a [StateError] when a diff position has no character, as Go returns
/// an error.
List<TextOperation> textSetString(TextState s, String value, String nodeId, HLC Function() nextClock) {
  final oldRunes = _visibleRunes(s);
  final newRunes = value.runes.toList();

  var prefix = 0;
  while (prefix < oldRunes.length && prefix < newRunes.length && oldRunes[prefix] == newRunes[prefix]) {
    prefix++;
  }
  var suffix = 0;
  while (suffix < oldRunes.length - prefix &&
      suffix < newRunes.length - prefix &&
      oldRunes[oldRunes.length - 1 - suffix] == newRunes[newRunes.length - 1 - suffix]) {
    suffix++;
  }

  final ops = <TextOperation>[];
  final del = oldRunes.length - prefix - suffix;
  if (del > 0) {
    final ref = textRefAt(s, prefix) ?? (throw StateError('crdt: text diff: no char at $prefix'));
    // textDeleteOp applies the delete to [s].
    ops.add(textDeleteOp(s, ref, del));
    nextClock();
  }
  final ins = String.fromCharCodes(newRunes.sublist(prefix, newRunes.length - suffix));
  if (ins.isNotEmpty) {
    TextRef? ref;
    if (prefix > 0) {
      ref = textRefAt(s, prefix - 1) ?? (throw StateError('crdt: text diff: no char at ${prefix - 1}'));
    }
    // textInsert applies the insert to [s].
    ops.add(textInsert(s, ref, ins, nodeId, nextClock()));
  }
  return ops;
}
